name: Build Zebra

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.GIT_TOKEN }}

    - name: Install Theos Dependencies
      run: brew install ldid fakeroot make

    - name: Install Theos
      uses: actions/checkout@v2
      with:
        repository: theos/theos
        path: theos
        submodules: recursive

    - name: Build Package
      env:
        THEOS: theos
      run: gmake package
